-- AlterTable
ALTER TABLE "User" ALTER COLUMN "photo" DROP NOT NULL,
ALTER COLUMN "color" DROP NOT NULL,
ALTER COLUMN "account" DROP NOT NULL,
ALTER COLUMN "total_bets" SET DEFAULT 0,
ALTER COLUMN "bets_won" SET DEFAULT 0,
ALTER COLUMN "finals_won" SET DEFAULT 0,
ALTER COLUMN "last_login" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "notifications" SET DEFAULT false;
